### ISSUE TITLE
Game Forwarders

### ISSUE THREAD

**Issue by captainbob32** [ForwarderFactory/wii#1]
This Repository Seems to be Good, But my Problem with This, is That There NOT Any Disc Game Forwarders Here AT ALL.
is It Alright if You Add Them? Because, I Think It Might Be Completed with Disc Game Forwarders.

(Say No If You Want, But I REALLY Think It Might Be Completed with Disc Game Forwarders)

**Comment by ghost** [comment]
I have no plans to add game disc forwarders for multiple reasons, and here's why:
-  I would have to add them for every Wii disc game ever made, which would be ridiculously time consuming, time that i don't have nowadays.
- The repository will never be complete, that's a fact I've realized since the beginning.
- Game discs are already preserved, because we have images of the discs and the physical discs which contain the forwarders.

That said, if you pull request, I will likely accept the PR! Closed.

**Comment by captainbob32** [comment]
Aw :(
Oh Well. Don't Need the Disc Game WADs Here, Anyways.

I'll Pull This Request

**Comment by captainbob32** [comment]
Oh Wait, I Don't Even Know How :(

**Comment by captainbob32** [comment]
Oh Well, Make It Stay Closed, Then :/

(I Made My Own Game WADs BTW)

**Comment by GabubuAvailable** [comment]
Stop being so weird captainbob. You literally "spammed" for a damn font on the thread about XFlak's problem on gbatemp. And why you asked if he died? I didn't even mentioned about XFlak being dead... Think before doing something man.

**Comment by captainbob32** [comment]
OK, Gabubu. btw, I'm a Fan

**Comment by captainbob32** [comment]
Also, I Asked if He Died Because I Just Want to Let People Know that He's Not Dead.

**Comment by captainbob32** [comment]
and Don't Worry, Gabubu. I Will Think before doing something.
